services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    restart:  unless-stopped
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    ports:
      - "${POSTGRES_PORT}:5432"  # Allow remote connections
    volumes:
      - postgres_data:/var/lib/postgresql
    user: postgres  # PostgreSQL specific user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 
    name: ${VOLUME_NAME}
    driver: local